"""Tenant registry — one isolated corpus and one voice per site.

Each site gets its own directory under ``data/sites/<site_id>/`` holding a
``site.json`` and a ``knowledge/`` corpus. The corpus is a plain
:class:`~shaggoth.knowledge.engine.KnowledgeBase` rooted at that directory,
which is the whole point: BM25 scoring is then computed over that site's
documents only.

Filtering a single global index by site cannot substitute for this. IDF and
the score normalisation are corpus-wide, so a site's own page is ranked
against ~800 encyclopedia articles and loses. That is not theoretical — asking
the live server "what is PurePulse" returned Smart Fortwo trim levels, because
the customer's brand name title-matched an unrelated scraped article.

Threading: the registry hands out long-lived KnowledgeBase instances to
request threads, so construction has to be exactly-once per site. The registry
lock is held only for dict operations; the (slow, I/O-bound) corpus scan runs
under a per-site lock so one tenant loading cannot stall every other tenant.
"""

from __future__ import annotations

import json
import secrets
import threading
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from ..config import DATA_DIR
from ..knowledge.engine import KnowledgeBase
from .verification import new_token, normalise_domain

SITES_DIR = DATA_DIR / "sites"

#: New sites start here. The default voice is deliberately not the rude one --
#: see personality/engine.py. A customer site must opt in to that, never
#: inherit it.
DEFAULT_PERSONALITY = "professional"

STATUS_PENDING = "pending"
STATUS_VERIFIED = "verified"


@dataclass
class SiteRecord:
    site_id: str
    domain: str
    token: str
    status: str = STATUS_PENDING
    personality: str = DEFAULT_PERSONALITY
    support_email: str = ""
    support_url: str = ""
    allow_general_fallback: bool = False
    verified_at: float = 0.0
    verified_method: str = ""
    created_at: float = field(default_factory=time.time)
    last_crawl_at: float = 0.0
    pages_indexed: int = 0

    @property
    def verified(self) -> bool:
        return self.status == STATUS_VERIFIED

    def public_dict(self) -> dict[str, Any]:
        """What is safe to hand back to a browser.

        The token is deliberately included: it is a verification challenge the
        owner has to publish anyway, not a credential. The site_id is public
        too -- it ships in the embed snippet. Neither authorises anything on
        its own; the domain allowlist is enforced server-side by Origin.
        """
        return asdict(self)


class SiteRegistry:
    """Maps ``site_id`` to its record and its isolated corpus."""

    def __init__(self, root: str | Path | None = None):
        self.root = Path(root) if root else SITES_DIR
        self.root.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._kb_locks: dict[str, threading.Lock] = {}
        self._kbs: dict[str, KnowledgeBase] = {}

    # ------------------------------------------------------------- storage

    def _site_dir(self, site_id: str) -> Path:
        # site_id is generated by us, but it reaches this from a URL path, so
        # refuse anything that could climb out of the sites directory.
        if not site_id or "/" in site_id or "\\" in site_id or "." in site_id:
            raise ValueError(f"invalid site_id: {site_id!r}")
        return self.root / site_id

    def _record_path(self, site_id: str) -> Path:
        return self._site_dir(site_id) / "site.json"

    def _write(self, record: SiteRecord) -> None:
        path = self._record_path(record.site_id)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write-then-rename so a crash cannot leave a half-written record that
        # fails to parse on the next start.
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(asdict(record), indent=2), encoding="utf-8")
        tmp.replace(path)

    # -------------------------------------------------------------- lookup

    def get(self, site_id: str) -> SiteRecord | None:
        try:
            path = self._record_path(site_id)
        except ValueError:
            return None
        if not path.exists():
            return None
        try:
            return SiteRecord(**json.loads(path.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, OSError, TypeError):
            return None

    def by_domain(self, domain: str) -> SiteRecord | None:
        for record in self.list_sites():
            if record.domain == domain:
                return record
        return None

    def list_sites(self) -> list[SiteRecord]:
        out: list[SiteRecord] = []
        for child in sorted(self.root.iterdir()):
            if child.is_dir():
                record = self.get(child.name)
                if record:
                    out.append(record)
        return out

    # ------------------------------------------------------------ mutation

    def register(self, raw_url: str) -> SiteRecord:
        """Create (or return) the pending site for ``raw_url``.

        Registering never starts a crawl. The site is ``pending`` until
        ownership is proven.
        """
        domain = normalise_domain(raw_url)
        with self._lock:
            existing = self.by_domain(domain)
            if existing:
                return existing
            record = SiteRecord(
                site_id=secrets.token_urlsafe(9).replace("-", "x").replace("_", "y"),
                domain=domain,
                token=new_token(),
            )
            (self._site_dir(record.site_id) / "knowledge").mkdir(
                parents=True, exist_ok=True
            )
            self._write(record)
            return record

    def update(self, site_id: str, **fields: Any) -> SiteRecord | None:
        with self._lock:
            record = self.get(site_id)
            if record is None:
                return None
            for key, value in fields.items():
                if hasattr(record, key):
                    setattr(record, key, value)
            self._write(record)
            return record

    def mark_verified(self, site_id: str, method: str) -> SiteRecord | None:
        return self.update(
            site_id,
            status=STATUS_VERIFIED,
            verified_at=time.time(),
            verified_method=method,
        )

    # -------------------------------------------------------------- corpus

    def knowledge_base(self, site_id: str) -> KnowledgeBase:
        """This site's isolated corpus, built at most once.

        The registry lock covers only the dict lookups. Building a
        KnowledgeBase runs a full corpus scan, so it happens under a per-site
        lock instead -- otherwise one tenant's first request would block every
        other tenant's.
        """
        with self._lock:
            existing = self._kbs.get(site_id)
            if existing is not None:
                return existing
            site_lock = self._kb_locks.setdefault(site_id, threading.Lock())

        with site_lock:
            # Re-check: another thread may have finished while we queued.
            with self._lock:
                existing = self._kbs.get(site_id)
            if existing is not None:
                return existing

            kb = KnowledgeBase(self._site_dir(site_id) / "knowledge")
            with self._lock:
                self._kbs[site_id] = kb
            return kb
